### ISSUE TITLE
HealthKit Info

### ISSUE THREAD

**Issue by sauchye** [sauchye/iosdev_notes#19]
当你的App使用`HealthKit`后打包上传`itunesconnect`出现这样的问题
`
使用权限 [com.apple.developer.healthkit] 的 App 必须为[Simplified Chinese]提供隐私政策。如果您的 App 不使用这些权限，请将它们从您的 App 中移除并上传新的二进制文件。`

先确定证书以及`Xcode`配置正确，一步一步检查原因 good luck :)

可参考:
http://blog.csdn.net/zzzzzdddddxxxxx/article/details/47722343
http://www.cocoachina.com/ios/20140915/9624.html
http://www.cnblogs.com/luoxiaofu/p/5259320.html

**Comment by Kelan-Ju** [comment]
在iTunes Connect的“App信息”栏里将“隐私政策网址(URL)”填上就可以了
![image](https://cloud.githubusercontent.com/assets/15358065/16544298/51111b3a-4133-11e6-8d99-223e14011f7f.png)
